openapi: 3.0.3
info:
  title: RIZZLER
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/category:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: Bracelet
                    slug: bracelet
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 2
                    name: Ring
                    slug: ring
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 3
                    name: Earrings
                    slug: earrings
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 4
                    name: Necklace
                    slug: necklace
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 5
                    name: Pendant
                    slug: pendant
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 6
                    name: Charm
                    slug: charm
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 7
                    name: Bangle
                    slug: bangle
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 8
                    name: Cufflinks
                    slug: cufflinks
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 9
                    name: Brooch
                    slug: brooch
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 10
                    name: Anklet
                    slug: anklet
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 11
                    name: Tiara
                    slug: tiara
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 12
                    name: 'Wedding Band'
                    slug: wedding-band
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 13
                    name: 'Engagement Ring'
                    slug: engagement-ring
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 14
                    name: 'Gemstone Jewelry'
                    slug: gemstone-jewelry
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 15
                    name: 'Pearl Jewelry'
                    slug: pearl-jewelry
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
      tags:
        - Endpoints
      security: []
  '/api/category/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Category not found.'
                properties:
                  error:
                    type: string
                    example: 'Category not found.'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the category.'
        example: magni
        required: true
        schema:
          type: string
  /api/product:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: '14K White Gold Bracelet with Akoya Pearl PNJ PAXMW000044'
                    slug: 14k-white-gold-bracelet-with-akoya-pearl-pnj-paxmw000044
                    description: 'This bracelet attracts...'
                    price: '30.00'
                    quantity: 10
                    material: 'Akoya Pearl'
                    size: '51'
                    stylecode: SP123
                    collection_id: 1
                    productcode: GVPAXMW000044
                    color: White
                    category_id: 2
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 2
                    name: '18K Gold Bracelet with Citrine PNJ Spring CTXMY000059'
                    slug: 18k-gold-bracelet-with-citrine-pnj-spring-ctxmy000059
                    description: 'With its bright yellow color, Citrine is a gemstone that holds optimistic and warm energy...'
                    price: '40.00'
                    quantity: 20
                    material: Citrine
                    size: '52'
                    stylecode: TS456
                    collection_id: 2
                    productcode: GVCTXMY000059
                    color: Blue
                    category_id: 1
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
                  -
                    id: 3
                    name: '18K Gold Bracelet with Ruby PNJ Spring RBXMY000180'
                    slug: 18k-gold-bracelet-with-ruby-pnj-spring-rbxmy000180
                    description: 'Refreshing the classic standard of 18K gold with a delicate Ruby stone, the PNJ bracelet embodies a fresh look, perfectly fitting to brighten the optimistic beauty of ladies. The perfect combination creates a luxurious gold bracelet, highlighting the wrist with a delicately set Ruby. This brilliance enhances the beauty of ladies, making them look charming and radiant when worn.'
                    price: '50.00'
                    quantity: 0
                    material: Ruby
                    size: '53'
                    stylecode: BK789
                    collection_id: 4
                    productcode: GVRBXMY000180
                    color: Gold
                    category_id: 4
                    created_at: '2024-12-17T17:32:35.000000Z'
                    updated_at: '2024-12-17T17:32:35.000000Z'
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: qlagjkmyjucversmalrpsrwl
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Consequatur vero fugiat nesciunt tempore qui quia et.'
                  nullable: true
                price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 11
                  nullable: false
                quantity:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 2
                  nullable: false
                material:
                  type: string
                  description: ''
                  example: itaque
                  nullable: true
                size:
                  type: string
                  description: ''
                  example: itaque
                  nullable: true
                stylecode:
                  type: string
                  description: ''
                  example: voluptas
                  nullable: true
                collection_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the collections table.'
                  example: null
                  nullable: true
                productcode:
                  type: string
                  description: ''
                  example: laudantium
                  nullable: true
                color:
                  type: string
                  description: ''
                  example: omnis
                  nullable: true
                category_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the product_categories table.'
                  example: mollitia
                  nullable: false
                images:
                  type: array
                  description: ''
                  example: null
                  items:
                    type: object
                    nullable: true
                    properties:
                      urls:
                        type: array
                        description: 'Must be a valid URL.'
                        example:
                          - 'https://parker.biz/quam-fuga-rerum-magni-laudantium-necessitatibus.html'
                        items:
                          type: string
                    required:
                      - urls
              required:
                - name
                - price
                - quantity
                - category_id
      security: []
  '/api/product/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Product not found.'
                properties:
                  error:
                    type: string
                    example: 'Product not found.'
      tags:
        - Endpoints
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the product.'
        example: 14k-white-gold-bracelet-with-akoya-pearl-pnj-paxmw000044
        required: true
        schema:
          type: string
  '/api/product/{slug}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hn
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Ut magnam qui corporis non labore ipsa est occaecati.'
                  nullable: true
                price:
                  type: number
                  description: 'Must be at least 0.'
                  example: 40
                  nullable: false
                quantity:
                  type: integer
                  description: 'Must be at least 0.'
                  example: 70
                  nullable: false
                material:
                  type: string
                  description: ''
                  example: et
                  nullable: true
                size:
                  type: string
                  description: ''
                  example: natus
                  nullable: true
                stylecode:
                  type: string
                  description: ''
                  example: fuga
                  nullable: true
                collection_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the collections table.'
                  example: null
                  nullable: true
                productcode:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                color:
                  type: string
                  description: ''
                  example: illum
                  nullable: true
                category_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the product_categories table.'
                  example: sapiente
                  nullable: false
              required:
                - name
                - price
                - quantity
                - category_id
      security: []
    parameters:
      -
        in: path
        name: slug
        description: 'The slug of the product.'
        example: 14k-white-gold-bracelet-with-akoya-pearl-pnj-paxmw000044
        required: true
        schema:
          type: string
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: amelie.brakus@example.com
                  nullable: false
                password:
                  type: string
                  description: ''
                  example: quia
                  nullable: false
              required:
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
